global:
  scrape_interval: 15s  # How frequently Prometheus will scrape metrics

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']  # Make sure the Go app is accessible here
