apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-admin
  namespace: iot-telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-admin
  template:
    metadata:
      labels:
        app: iot-admin
    spec:
      containers:
      - name: iot-admin
        image: ghcr.io/raghiba/iot-telemetry-admin:latest
        ports:
        - containerPort: 8081
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: admin-postgres-secret
                key: POSTGRES_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: admin-postgres-secret
                key: POSTGRES_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: admin-postgres-secret
                key: POSTGRES_DB
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: admin-postgres-secret
                key: POSTGRES_PORT
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: admin-postgres-secret
                key: HOST
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: admin-postgres-secret
                key: PORT
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: admin-postgres-secret
                key: JWT_SECRET