name: Deploy Consumer
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup kubectl and deploy
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG_SECRET }}
      - name: Apply kubernetes Manifests
        run: |
          kubectl apply -f .k8s/consumer/deployment.yaml -n iot-telemetry
          kubectl apply -f .k8s/consumer/service.yaml -n iot-telemetry
          kubectl apply -f .k8s/consumer/ingress.yaml -n iot-telemetry